apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ec2-app
  template:
    metadata:
      labels:
        app: ec2-app
    spec:
      containers:
      - name: ec2-container
        image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/golang-api:latest
        ports:
        - containerPort: 8080
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ec2-service
spec:
  selector:
    app: ec2-app
  ports:
    - port: 8080
      targetPort: 8080