apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: a158297c322ad4fbd9b4906b660a4063-683422208.ap-northeast-2.elb.amazonaws.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /healthz
        backend:
          service:
            name: golang-api
            port:
              number: 8080
      - pathType: ImplementationSpecific
        path: /v1/dummy
        backend:
          service:
            name: golang-api
            port:
              number: 8080
