apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-deployment
  namespace: ec2-fargate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec2-app
  template:
    metadata:
      labels:
        app: ec2-app
    spec:
      containers:
      - name: ec2-container
        image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/golang-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fargate-deployment
  namespace: ec2-fargate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fargate-app
  template:
    metadata:
      labels:
        app: fargate-app
    spec:
      containers:
      - name: fargate-container
        image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/golang-api:latest
        ports:
        - containerPort: 8080