apiVersion: v1
kind: Service
metadata:
  name: ec2-service-a
  namespace: ec2
spec:
  type: LoadBalancer
  selector:
    app: ec2-app-a
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fargate-service-a
  namespace: fargate
spec:
  type: LoadBalancer
  selector:
    app: fargate-app-a
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ec2-service-b
  namespace: ec2
spec:
  type: LoadBalancer
  selector:
    app: ec2-app-b
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fargate-service-b
  namespace: fargate
spec:
  type: LoadBalancer
  selector:
    app: fargate-app-b
  ports:
  - port: 8080
    targetPort: 8080