apiVersion: v1
kind: Service
metadata:
  name: ec2-service
  namespace: ec2-fargate
spec:
  type: LoadBalancer  
  selector:
    app: ec2-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service  
metadata:
  name: fargate-service
  namespace: ec2-fargate
spec:
  selector:
    app: fargate-app
  ports:
    - port: 8080
      targetPort: 8080
